[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
wasm-debug = "build --lib --target wasm32-unknown-unknown"
schema = "run --bin schema"

# OLDER:
# wasm = "build --release --target wasm32-unknown-unknown"
# wasm-debug = "build --target wasm32-unknown-unknown"
# schema = "run --example schema"